language: ruby
rvm:
  - 2.1.3
env:
  - DB=mysql
before_script:
  - cp test/travisconfig/database.yml config/database.yml
  - cp test/travisconfig/secrets.rb config/initializers/secrets.rb
  - mysql -e 'create database greasyforktest'
  - mysql greasyforktest < db/structure.sql
