---
:concurrency: 2
:queues:
  - default
  - low
  - background

tasks: &tasks
  ScriptDuplicateCheckerQueueingJob:
    interval: ["10s"]
    queue: background
    description: 'Find scripts to check for duplicates'

:schedule:
  <<: *tasks
